# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
add_subdirectory(async_ping_rx)
add_subdirectory(async_ping_tx)
add_subdirectory(bayer_demosaic)
add_subdirectory(bayer_demosaic_gpu_resident)
add_subdirectory(format_converter)
add_subdirectory(format_converter_gpu_resident)
add_subdirectory(gxf_codelet)
add_subdirectory(holoviz)
add_subdirectory(raw_image_processor)
add_subdirectory(inference)
add_subdirectory(inference_processor)
add_subdirectory(gpu_resident_inference)
add_subdirectory(ping_rx)
add_subdirectory(ping_tx)
add_subdirectory(ping_tensor_rx)
add_subdirectory(ping_tensor_tx)
add_subdirectory(segmentation_postprocessor)
add_subdirectory(test_ops)
add_subdirectory(v4l2_video_capture)
add_subdirectory(video_io)
add_subdirectory(video_stream_recorder)
add_subdirectory(video_stream_replayer)
