/*
 * SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

syntax = "proto3";

package holoscan.distributed;

import "system_resource.proto";
import "result.proto";

message FragmentAllocationRequest {
  string worker_ip = 1;
  string worker_port = 2;
  repeated string fragment_names = 3;
  AvailableSystemResource available_system_resource = 4;
}

message FragmentAllocationResponse {
  Result result = 1;
}

message WorkerExecutionFinishedRequest {
  string worker_ip = 1;
  string worker_port = 2;
  Result status = 3;
}

message WorkerExecutionFinishedResponse {
  Result result = 1;
}

message InitiateShutdownRequest {
  string fragment_name = 1;  // Name of fragment requesting shutdown
}

message InitiateShutdownResponse {
  Result result = 1;
}

service AppDriverService {
  rpc AllocateFragments(FragmentAllocationRequest) returns (FragmentAllocationResponse) {}
  rpc ReportWorkerExecutionFinished(WorkerExecutionFinishedRequest) returns (WorkerExecutionFinishedResponse) {}
  rpc InitiateShutdown(InitiateShutdownRequest) returns (InitiateShutdownResponse) {}
}
