/*
 * SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

syntax = "proto3";

package holoscan.distributed;

enum IOType
{
    INPUT = 0;
    OUTPUT = 1;
}

enum ConnectorType
{
    DEFAULT = 0;
    DOUBLE_BUFFER = 1;
    UCX = 2;
    PUBSUB = 3;
}

message ConnectorArg
{
    string key = 1;
    oneof value {
        string str_value = 2;
        int32 int_value = 3;
        uint32 uint_value = 4;
        double double_value = 5;
    }
}

message ConnectionItem {
    string name = 1;
    IOType io_type = 2;
    ConnectorType connector_type = 3;
    repeated ConnectorArg args = 4;
}
