/*
 * SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

syntax = "proto3";

package holoscan.distributed;

message MultiFragmentPortInfo
{
    message OperatorPortInfo
    {
        optional string operator_name = 1;
        repeated string input_names = 2;
        repeated string output_names = 3;
        repeated string receiver_names = 4;
    }

    message FragmentPortInfo
    {
        optional string fragment_name = 1;
        repeated OperatorPortInfo operators_info = 2;
    }

    repeated FragmentPortInfo targets_info = 1;
}
