#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This script builds and runs the examples to make sure that the Holoscan SDK is correctly
# installed and examples can be built and run correctly
# NOTE: This is meant to be called from an installation of the SDK, not from the git repository

# Get path to the examples. This assumes the directory is where the script is located
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
source_dir=$(realpath "$SCRIPT_DIR/..")

# Compile the examples
# Note: the examples/CMakeLists.txt file automatically discovers all CMakeLists.txt files in subdirectories,
#       so we specify ../examples-build as the build directory to prevent the 'examples-build' folder from being treated
#       as an example and including all CMakeLists.txt files within it.
build_dir=${source_dir}/../examples-build
cmake -S ${source_dir} -B ${build_dir}
cmake --build ${build_dir} -j

# Run CTest
ctest --test-dir ${build_dir} $*
