/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// DDS type: device pointer descriptor plus buffer size.
// Include the descriptor type from the SDK IPC (holoscan::ipc) library IDL.

#include "pointer_descriptor.idl"

module holoscan
{
    module ipc
    {
        module dds_example
        {
            struct CudaBuffer
            {
                holoscan::ipc::PointerDescriptor descriptor;
                unsigned long size;
            };
        };
    };
};
