#!/bin/bash
#
# SPDX-FileCopyrightText: Copyright (c) 2022-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

if [ -e ${SCRIPT_DIR}/debug_env.sh ]; then
    # User can place debug_env.sh in the same directory as this script (.vscode/debug_env.sh would be ignored in git repo)
    . ${SCRIPT_DIR}/debug_env.sh
fi

if [ -e ${SCRIPT_DIR}/../.python-version ] && command -v pyenv > /dev/null; then
    # Need to init in script: https://github.com/pyenv/pyenv-virtualenv/issues/204
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    # Above will do `pyenv activate $(cat ${SCRIPT_DIR}/../.python-version)`.
fi
echo "Python: $(python3 -c "import sys;print(sys.executable)")"

# Instead of using `exec env python3 "$@"`, we employ the following command to ensure the binary's
# path is correctly set and to maintain the correct handling of arguments that include spaces.
exec /bin/bash -c 'python3 "$@"' _ "$@"
