%YAML 1.2
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
inference_parameters:
  model_path_map:
    "model_1": "./examples/bring_your_own_model/model/identity_model.onnx"
  pre_processor_map:
    "model_1": "input_1"
  inference_map:
    "model_1": "output_1"
tensors:
  input_1:
    dim: "512,512,3"
    dtype: kFloat32
  output_1:
    dim: "512,512,3"
    dtype: kFloat32
