#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2022-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

set -e

# This script downloads a sample dataset for some of the examples.

# Creates the data directory
# Note: we assume this script is installed in the `examples` folder
SCRIPT_DIR="$(dirname $(realpath $0))"
DATA_DIR=${SCRIPT_DIR}/../data
mkdir -p ${DATA_DIR}

# Download the racerx sample data
racerx_version="20231009"
racerx_md5="b67492afea29610105995c4c27bd5a05"

${SCRIPT_DIR}/../bin/download_ngc_data \
    --url https://edge.urm.nvidia.com/artifactory/sw-holoscan-thirdparty-generic-local/data/racerx/racerx_${racerx_version}.zip \
    --download_dir ${DATA_DIR} \
    --download_name racerx \
    --md5 ${racerx_md5}
