#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

# This script downloads a sample dataset for some of the examples.

# Creates the data directory
# Note: we assume this script is installed in the `examples` folder
SCRIPT_DIR="$(dirname $(realpath $0))"
DATA_DIR=${SCRIPT_DIR}/../data
mkdir -p ${DATA_DIR}

# Download the racerx sample data
racerx_version="20231009"
racerx_md5="86cd7e5477bb9eaa0cfc0547912d77b2"

${SCRIPT_DIR}/../bin/download_ngc_data \
    --url https://api.ngc.nvidia.com/v2/resources/nvidia/clara-holoscan/holoscan_racerx_video/versions/${racerx_version}/zip \
    --download_dir ${DATA_DIR} \
    --download_name racerx \
    --md5 ${racerx_md5}
